import Providers from "@/hooks/Providers";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({ weight: "400" });

export const metadata = {
  title: "todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
